### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by oliviermeslin** [JosepER/ntts2023_julia_for_official_statistics#2]
Hi,

The links to the benchmark codes in the Readme seem to be broken:

- [Repository for Julia computations](https://github.com/JosepER/ntts_2023_benchmarking_julia)
- [Repository for R computations](https://github.com/JosepER/ntts_2023_benchmarking_R)

Maybe the repositories are not public?

**Comment by JosepER** [comment]
Yes. The repos should be public now. Thanks!
